# Generated by Django 2.0.6 on 2018-09-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180907_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_detail',
            new_name='comment_text',
        ),
    ]
