# Generated by Django 2.1.4 on 2018-12-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181228_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_type',
            name='source_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Source_Type'),
        ),
    ]
